### ISSUE TITLE
Statusanzeige für Effekte

### ISSUE THREAD

**Issue by jhewebdev** [MaikFischer/TeamPentagon#8]
**Statusanzeige auf dem Gamescreen, um dem Spieler zu zeigen welche Effekte/Boni er gerade besitzt**

### Tasks

- Neue Label auf Gamescreen erstellen
   - Bonus: _currentBonus_
   - Multi: _currentMultiplier_
   - perSecond: _currentCreditsPerSecond_
- Methode/n zum Updaten der Werte schreiben (siehe `updateScore()` oder `updatePrice()` in game.cs)
- Testen und bei Bedarf Fehler beheben

**Comment by MaikFischer** [comment]
Statusanzeige fertig gestellt.
